baseurl = "https://diegojromerolopez.github.io"
DefaultContentLanguage = "en"
title = "Diego J.'s Software Tar Pit"
theme = "anatole"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  title = "Diego J.'s Software Tar Pit"
  author = "Diego J. Romero-López"
  description = "Diego J.'s rambling thoughts about software"
  profilePicture = "/img/diegoj-logo.png"
  favicon = "/img/favicon.ico"
  # Let's add standard Anatole features
  customCss = []
  customJs = []
  # Enable dark mode
  darkMode = true

[params.mermaid]
  enable = true


[[params.socialIcons]]
  icon = "fab fa-github"
  title = "GitHub"
  url = "https://github.com/diegojromerolopez"

[[params.socialIcons]]
  icon = "fab fa-linkedin"
  title = "LinkedIn"
  url = "https://www.linkedin.com/in/diegojromerolopez/"

[[params.socialIcons]]
  icon = "fab fa-x-twitter"
  title = "X (Twitter)"
  url = "https://x.com/diegojromerolop"

[[params.socialIcons]]
  icon = "fab fa-bluesky"
  title = "Bluesky"
  url = "https://bsky.app/profile/diegojromerolopez.bsky.social"

[languages]
  [languages.en]
    contentDir = "content/en" # English
    label = "English"
    weight = 1
  [languages.es]
    contentDir = "content/es" # Spanish
    label = "Español"
    weight = 2

[frontmatter]
  date = [':filename', ':default']

[permalinks]
  post = "/blog/:year/:month/:title/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2

[[menu.main]]
    name = "CV"
    url = "/cv.pdf"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
